---
title: "bootstrapped_community_means"
author: "Liyenne"
date: "2025-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup
```{r}
script_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(file.path(script_dir, "..", ".."))

# data handling
require(tidyverse)

# analysis
require(traitstrap)

# visualization
require(ggplot2)
```

# Data import
```{r data import}
# trait data
trait_data <- read_csv("2_data/2_clean_data/trait_data_w.csv")

trait_data_long <- read_csv("2_data/2_clean_data/trait_data_l.csv")

trait_data_pooled <- read_csv("2_data/2_clean_data/pooled_trait_data_w.csv")

trait_data_pooled_long <- read_csv("2_data/2_clean_data/pooled_trait_data_l.csv")
```

```{r}
# community composition data (long)
community_data <- read_csv("2_data/2_clean_data/community_data_2023_l.csv") 
```

# Bootstrapping traits
## trait fill 
### no chem
```{r}
filled_traits <- trait_fill(
comm = community_data, traits = trait_data_long,
scale_hierarchy = c("habitat", "site", "treatment", "plot"),
taxon_col = c("species", "genus", "family"), value_col = "trait_value",
trait_col = "trait", abundance_col = "hits", complete_only = TRUE, leaf_id = "code"
)
autoplot(filled_traits)
```

```{r}
trait_missing(filled_trait = filled_traits, comm = community_data)
```

```{r}
trait_fit_distributions(filled_traits, distribution_type = "normal")
```

```{r}
boot_traits <- trait_np_bootstrap(filled_traits = filled_traits, nrep = 10, sample_size = 100)
```

### with chem
```{r}
filled_traits_pooled <- trait_fill(
comm = community_data, traits = trait_data_pooled_long,
scale_hierarchy = c("habitat", "site", "treatment", "plot"),
taxon_col = c("species", "genus", "family"), value_col = "trait_value",
trait_col = "trait", abundance_col = "hits", complete_only = TRUE, leaf_id = "ID"
)
autoplot(filled_traits_pooled)
```

```{r}
trait_missing(filled_trait = filled_traits_pooled, comm = community_data)
```

```{r}
boot_traits_pooled <- trait_np_bootstrap(filled_traits = filled_traits_pooled, nrep = 10, sample_size = 100)

trait_summarise_boot_moments(boot_traits_pooled)
```

# community weighted averages
are shifts in community averages driven by species adaptation or species composition differences?
## no chem
```{r}
boot_traits %>% 
  ggplot(aes(x = habitat, y = mean, fill = treatment)) + 
  geom_boxplot() + 
  facet_wrap(~ trait, scales = "free") + 
  theme_classic() +
  theme(panel.spacing = unit(.0, "lines"),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        legend.position = "bottom",
        legend.margin = margin(t = -8),
        strip.background = element_rect(color = "black", size = 1),
        axis.text.x = element_text(angle = 25, hjust = 1))

ggsave("3_output/Figures/bootstrapped_traits.svg", height = 7, width = 7)
```

## with chem
```{r}
boot_traits_pooled %>% 
  ggplot(aes(x = habitat, y = mean, fill = treatment)) + 
  geom_boxplot() + 
  facet_wrap(~ trait, scales = "free") + 
  theme_classic() +
  theme(panel.spacing = unit(.0, "lines"),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        legend.position = "bottom",
        legend.margin = margin(t = -8),
        strip.background = element_rect(color = "black", size = 1),
        axis.text.x = element_text(angle = 25, hjust = 1))

ggsave("3_output/Figures/bootstrapped_traits_pooled.svg", height = 7, width = 7)
```