---
title: "leaf_area"
author: "Liyenne"
date: "2024-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = "hide")
```

```{r}
#devtools::install_github("richardjtelford/LeafArea")
library(LeafArea)
```

```{r message=TRUE, warning=TRUE}
loop.files <-  function(files){

  file.copy(files, new.folder)
  if(grepl("-NA$", files)){
    newfile <- basename(files)
    file.rename(paste0(new.folder, "/", newfile), paste0(new.folder,
                                                         "/", gsub("-NA$", "", newfile)))
  }
  print(files)
  area <- try(run.ij(set.directory = new.folder, distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 50, trim.pixel.right = 50, trim.pixel.top = 1150, save.image = TRUE))
  # more cropping
  #area <- try(run.ij(set.directory = new.folder, distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 200, trim.pixel2 = 0, save.image = TRUE))

  if(inherits(area, "try-error")){
    return(data.frame(LeafArea = NA))
  }
  file.copy(dir(new.folder, full.names = TRUE, pattern = "\\.tif"), output.folder)
  Sys.sleep(0.1)
  if(any(!file.remove(dir(new.folder, full.names = TRUE) ))) stop()
  res <- data.frame(dir = dirname(files), ID = names(unlist(area[[2]])), LeafArea = (unlist(area[[2]])))
  return(res)
}
```

```{r include = FALSE}
# test
ex.dir <- "C:/Users/liha3090/analysis_ready/"
ex.dir <- eximg()

res <- run.ij(set.directory = ex.dir, save.image = TRUE)
```

```{r}
dd <- run.ij(set.directory = "C:/Users/liha3090/leaf_scans/test", distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 50, trim.pixel.right = 50, trim.pixel.top = 1250, save.image = TRUE)
dd$summary
```


```{r results='hide', warning=TRUE}
# run leaf scans round1
dd1 <- run.ij(set.directory = "C:/Users/liha3090/leaf_scans/analysis_ready/round1", distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 50, trim.pixel.right = 50, trim.pixel.top = 1250, save.image = TRUE)
dd1 <- dd1$summary

# run leaf scans round2
dd2 <- run.ij(set.directory = "C:/Users/liha3090/leaf_scans/analysis_ready/round2", distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 50, trim.pixel.right = 50, trim.pixel.top = 1250, save.image = TRUE)
dd2 <- dd2$summary

# run leaf scans round3
dd3 <- run.ij(set.directory = "C:/Users/liha3090/leaf_scans/analysis_ready/round3", distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 50, trim.pixel.right = 50, trim.pixel.top = 1250, save.image = TRUE)
dd3 <- dd3$summary

# run leaf scans round4
dd4 <- run.ij(set.directory = "C:/Users/liha3090/leaf_scans/analysis_ready/round4", distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 50, trim.pixel.right = 50, trim.pixel.top = 1250, save.image = TRUE)
dd4 <- dd4$summary

# run leaf scans round5
dd5 <- run.ij(set.directory = "C:/Users/liha3090/leaf_scans/analysis_ready/round5", distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 50, trim.pixel.right = 50, trim.pixel.top = 1250, save.image = TRUE)
dd5 <- dd5$summary

# run leaf scans round6
dd6 <- run.ij(set.directory = "C:/Users/liha3090/leaf_scans/analysis_ready/round6", distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 50, trim.pixel.right = 50, trim.pixel.top = 1250, save.image = TRUE)
dd6 <- dd6$summary

# run leaf scans check
dd6 <- run.ij(set.directory = "C:/Users/liha3090/leaf_scans/scan_check", distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 100, trim.pixel.right = 100, trim.pixel.top = 1450, save.image = TRUE)
dd6 <- dd6$summary

LA2024 <- rbind(dd1, dd2, dd3, dd4, dd5, dd6)
#write.csv(LA2024, "../../3_output/1_data_products/leaf_area_2024.csv")
```

```{r}
list.of.files <- dir(path = paste0("C:/Users/liha3090/leaf_scans/analysis_ready/"), pattern = "jpeg|jpg", recursive = TRUE, full.names = TRUE)
new.folder <- "C:/Users/liha3090/leaf_scans/temp/"
output.folder <- "C:/Users/liha3090/leaf_scans/"
```

```{r}
LA_24 <- plyr::ldply(list.of.files, loop.files)
```


```{r}
# leaf scans for Agnes
dd <- run.ij(set.directory = "C:/Users/liha3090/leaf_scans/analysis_ready/Agnes/", distance.pixel = 237, known.distance = 2, log = TRUE, low.size = 0.005, trim.pixel = 50, trim.pixel.right = 50, trim.pixel.top = 1250, save.image = TRUE)
dd <- dd$summary

write.csv(dd, "../../3_output/1_data_products/leaf_area_Agnes.csv")
```


