---
title: "global_data"
author: "Liyenne"
date: "2025-06-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup
```{r}
script_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(file.path(script_dir, "..", "..")); rm(script_dir)

# data handling
require(readr)
require(rtry)
require(tidyverse)
require(WorldFlora)

# analysis
require(traitstrap)

# visualization
require(ggplot2)
```

# Data import
```{r data import}
# trait data
trait_data <- read_csv("2_data/2_clean_data/trait_data_w.csv")

trait_data_long <- read_csv("2_data/2_clean_data/trait_data_l.csv")

trait_data_pooled <- read_csv("2_data/2_clean_data/pooled_trait_data_w.csv")

trait_data_pooled_long <- read_csv("2_data/2_clean_data/pooled_trait_data_l.csv")

global_traits <- read_csv("2_data/1_raw_data/global_traits/TTT_cleaned_dataset_v1.csv")

try_data <- rtry_import("../../1_data/TRY_data/42107.txt") #%>% 
#  select(ObservationID, SpeciesName, TraitID, TraitName, #OrigValueStr) %>% 
#  filter(TraitID != 42) %>% 
#  na.omit() %>% 
#  group_by(ObservationID) %>% 
#  pivot_wider(names_from = TraitName, values_from = OrigValueStr)
```

```{r}
# community composition data (long)
community_data <- read_csv("2_data/2_clean_data/community_data_2023_l.csv") 
```

# Wrangling
```{r}
global_traits_w <- global_traits %>%
  select(2:4, SiteName, Trait, Value) %>% 
  pivot_wider(names_from = Trait, values_from = Value) %>% 
  
```

# taxonomic data
```{r}
classification <- read_delim("../../1_data/TRY_data/classification.csv", delim = "\t")
```

# TRY
```{r}
#try_data <- rtry_import("../../1_data/TRY_data/42107.txt") %>% 
#  rtry_remove_dup()

try_summary <- try_data %>% 
  rtry_explore(TraitName, AccSpeciesName)

num_traits <- try_data %>% 
  rtry_exclude(ErrorRisk >= 3, baseOn = ObsDataID) %>% # exclude outliers according to error risk
  rtry_select_row(complete.cases(TraitID) & complete.cases(StdValue)) %>% 
  rtry_select_col(ObservationID, AccSpeciesID, AccSpeciesName, TraitID, TraitName, StdValue, UnitName)  # remove anciliary data
  

georef <- try_data %>%
  rtry_exclude(ErrorRisk >= 3, baseOn = ObsDataID) %>% 
  rtry_select_anc(59, 60) # keep lon/lat

num_traits_georef <- rtry_join_left(num_traits, georef, baseOn = ObservationID) # add lon/lat to trait data

try_data_w <- rtry_trans_wider(num_traits_georef, names_from = c(TraitID, TraitName, UnitName), values_from = c(StdValue), values_fn = list(StdValue = mean)) # transform to wide 
 
try_data_w <- try_data_w %>% 
   rename(SLA = `3116_Leaf area per leaf dry mass (specific leaf area, SLA or 1/LMA): petiole included_mm2 mg-1`,
          N = `14_Leaf nitrogen (N) content per leaf dry mass_mg/g`,
          d15N = `78_Leaf nitrogen (N) isotope signature (delta 15N)_per mill`,
          C = `13_Leaf carbon (C) content per leaf dry mass_mg/g`,
          d13C = `89_Leaf carbon isotope signature (delta 13C)_per mill`,
          CN_ratio = `146_Leaf carbon/nitrogen (C/N) ratio_g g-1`,
          height = `3106_Plant height vegetative_m`,
          root_depth = `6_Root rooting depth_m`,
          root_length = `1079_Root length_cm`, 
          LDMC = `47_Leaf dry mass per leaf fresh mass (leaf dry matter content, LDMC)_g/g`)
```


# exploration
```{r}
try_data_w <- try_data_w %>% 
  filter(height > 0)
```

```{r}
species_traits <- try_data_w %>% 
  group_by(AccSpeciesName) %>% 
  summarise(across(c(height, LDMC, SLA, N, d15N, C, d13C, CN_ratio), 
                   ~ mean(.x, na.rm = TRUE), 
                   .names = "{.col}")) %>% 
  column_to_rownames(var = "AccSpeciesName")
```

```{r}
try_data_w %>% 
  filter(N < 400) %>% 
  ggplot(aes(y = N)) + 
  geom_boxplot()

trait_data_pooled %>% 
  filter(species == "Empetrum nigrum") %>% 
  ggplot(aes(x = treatment, y = CN_ratio)) + 
  geom_boxplot()
```

